<?php

/**
 * aEcwidProductSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEcwidProductSlotTable extends PluginaEcwidProductSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEcwidProductSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEcwidProductSlot');
    }
}