<?php

/**
 * aPollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPollTable extends PluginaPollTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPoll');
    }
}