<?php

/**
 * aPollSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPollSlotTable extends PluginaPollSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPollSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPollSlot');
    }
}