<?php

/**
 * aPollChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPollChoiceTable extends PluginaPollChoiceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPollChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPollChoice');
    }
}