<?php

/**
 * BaseaPollChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $count
 * @property integer $poll_id
 * @property aPoll $Poll
 * 
 * @method string      getName()    Returns the current record's "name" value
 * @method integer     getCount()   Returns the current record's "count" value
 * @method integer     getPollId()  Returns the current record's "poll_id" value
 * @method aPoll       getPoll()    Returns the current record's "Poll" value
 * @method aPollChoice setName()    Sets the current record's "name" value
 * @method aPollChoice setCount()   Sets the current record's "count" value
 * @method aPollChoice setPollId()  Sets the current record's "poll_id" value
 * @method aPollChoice setPoll()    Sets the current record's "Poll" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaPollChoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_poll_choice');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('poll_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('aPoll as Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}